apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-core
  namespace: omni-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-core
  template:
    metadata:
      labels:
        app: ai-core
    spec:
      containers:
        - name: ai-core
          image: ghcr.io/your-org/ai-core:staging
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: postgresql://user:password@postgres:5432/omni
            - name: REDIS_URL
              value: redis://redis:6379/0
            - name: QDRANT_URL
              value: http://qdrant:6333
          readinessProbe:
            httpGet:
              path: /v1/health
              port: 8000
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /v1/health
              port: 8000
            initialDelaySeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: ai-core
  namespace: omni-staging
spec:
  selector:
    app: ai-core
  ports:
    - port: 8000
      targetPort: 8000


