apiVersion: batch/v1
kind: CronJob
metadata:
  name: pg-backup
spec:
  schedule: "0 */6 * * *" # every 6 hours
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 600
  ttlSecondsAfterFinished: 300
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          automountServiceAccountToken: false
          serviceAccountName: backup
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            fsGroup: 10001
            runAsNonRoot: true
            runAsUser: 10001
          restartPolicy: OnFailure
          containers:
            - name: pg-backup
              image: amazon/aws-cli:2.15.0
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                runAsNonRoot: true
                runAsUser: 10001
                runAsGroup: 10001
                capabilities:
                  drop: ["ALL"]
              envFrom:
                - secretRef:
                    name: backup-secrets
              command: ["/bin/bash", "-lc"]
              args:
                - |
                  set -euo pipefail
                  /bin/bash /scripts/pg_backup.sh
              volumeMounts:
                - name: backup-scripts
                  mountPath: /scripts
                  readOnly: true
              resources:
                requests:
                  cpu: "100m"
                  memory: "128Mi"
                limits:
                  cpu: "300m"
                  memory: "256Mi"
          volumes:
            - name: backup-scripts
              configMap:
                name: backup-scripts

