apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-agent-templates
data:
  gateway.tmpl: |
    {{- with secret "kv/gateway" -}}
    export JWT_SECRET="{{ .Data.data.JWT_SECRET }}"
    export AI_CORE_URL="{{ .Data.data.AI_CORE_URL }}"
    {{- end -}}
  gateway-sentry.tmpl: |
    {{- with secret "kv/gateway/sentry" -}}
    export SENTRY_DSN="{{ .Data.data.DSN }}"
    {{- end -}}

