apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: omni-pro
resources:
  - ../../staging/gateway-deployment.yaml
  - ../../staging/ai-core-deployment.yaml
  - ../../staging/frontend-deployment.yaml
patches:
  - target:
      kind: Deployment
      name: gateway
    patch: |-
      - op: add
        path: /spec/template/metadata/annotations
        value:
          rollout.canary/weight: "25%"
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      kind: Deployment
      name: ai-core
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2


